#! /usr/bin/sh

if [! -d "~/.iex" ]; 
  mkdir ~/.iex
  echo "Directory ~/.iex created"
fi

if cp -R ./iex ~/.iex/; then
  echo "Files copied to ~/.iex dir \n"
else
  echo "Error in copying file :("
fi

if cp iex.exs ~/.iex.exs; then
  echo "Created .iex.exs file inside home"
else
  [! -f "~/.iex.exs" ] && echo "Something bad happened :("
fi

echo "Installing Process Finished :)"
echo "Github: https://github.com/blackode/custom-iex"
echo "Contact: mrblackode@gmail.com"
echo "Thank You :)"



